export const STEP_LABELS: { label: string; sub: string }[] = [
  { label: 'Application Setup', sub: 'Define your settings and preferences' },
  { label: 'Access Control', sub: 'Establish admin roles and secure access' },
  { label: 'Brand Personalization', sub: 'Apply your identity and visual themes' },
  { label: 'Feature Selection', sub: 'Choose modules to your operations' },
  { label: 'Finalize & Deploy', sub: 'Review configuration and go live confidently' },
];

export const INITIAL_APP_BASICS_DATA = {
  appName: '',
  subdomain: '',
  addressLine: '',
  country: '',
  state: '',
  city: '',
  applicationCategory: [],
  projectType: '',
  ownershipType: '',
  tariffPlans: [],
  billingMode: '',
  meteringType: '',
};

export const INITIAL_ADMIN_ACCESS_DATA = {
  adminFirstName: '',
  adminLastName: '',
  adminEmail: '',
  adminPhone: '',
  adminPassword: '',
  adminConfirmPassword: '',
  adminUsername: '',
  adminRole: '',
  newAccountRole: '',
  sendWelcomeEmail: false,
  newAccountFirstName: '',
  newAccountLastName: '',
  newAccountUsername: '',
  newAccountEmail: '',
  newAccountPhone: '',
  newAccountPassword: '',
  newAccountConfirmPassword: '',
  newAccounts: [],
};

export const INITIAL_BRANDING_DATA = {
  companyName: '',
  companyWebsite: '',
  appLogo: null,
  appFavicon: null,
  // Defaulted color fields for BrandPersonalization
  colorPrimaryBg: '#efefef',
  colorPrimaryBgLight: '#dce7ec',
  colorPrimaryLightest: '#f5f8fc',
  colorSecondary: '#55b56c',
  colorSecondaryLight: '#bbe1c4',
  colorSecondaryPositive: '#029447',
  colorSecondaryPositiveLight: 'rgba(52, 199, 89, 0.15)',
  colorTextPrimary: '#262626',
  colorTextSecondary: '#7e7e7e',
  colorPrimaryBorder: '#e9efff',
  colorWarning: '#ed8c22',
  colorWarningAlt: '#ffd108',
  colorWarningLight: 'rgba(255, 180, 0, 0.15)',
  colorDanger: '#dc272c',
  colorDangerAlt: '#ff7c5c',
  colorDangerLight: 'rgba(231, 45, 63, 0.1)',
  colorInfo: 'none',
  colorNeutralDark: '#3c3c3c',
  colorNeutralDarker: '#262626',
  colorNeutralLightest: '#ffffff',
  colorAccentLight: 'rgba(0, 209, 178, 0.05)',
  colorShadowPrimary: '#dce4ef',
  colorShadowSecondary: '#dce4ef',
  colorPrimaryDark: '#041328',
  colorPrimaryDarkLight: '#06152d',
  colorDarkPrimary: '#476189',
  colorDarkSecondary: '#476189',
  colorDarkBorder: '#091b3b',
  colorPrimaryGradient: 'linear-gradient(135deg, var(--colorSecondaryLight), var(--colorSecondaryLightestTransperent))',
  colorPrimaryDarkGradient: 'linear-gradient(135deg, var(--colorPrimaryLight), var(--colorSecondaryLightestTransperent))',
  colorGradientSecondary: 'linear-gradient(135deg, var(--color-secondary), var(--color-secondary-light))',
  colorStatIconGradient: 'linear-gradient(0deg, rgb(187 225 196), rgba(22, 59, 124, 0))',
  appDescription: '',
  contactEmail: '',
  contactPhone: '',
  enableDarkMode: false,
  enableMultiLanguage: false,
};

export const INITIAL_MODULE_DATA = {
  modules: [] as string[],
};

export const STEP_COUNT = 5; 